baseURL = "https://www.empowertitleco.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Empower Title"
enableRobotsTXT = true

[[menu.desktop]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.desktop]]
    identifier = "Title 101"
    name = "Title 101"
    url = "/title-101/"
    weight = 2
[[menu.desktop]]
    identifier = "Underwriting"
    name = "Underwriting"
    url = "/underwriting/"
    weight = 3
[[menu.desktop]]
    identifier = "Title Calculators"
    name = "Title Calculators"
    url = "/title-calculator/"
    weight = 4
[[menu.desktop]]
    identifier = "Locations"
    name = "Locations"
    url = "/locations/"
    weight = 5
[[menu.desktop]]
    identifier = "Contact Us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 6
[[menu.mobile]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.mobile]]
    identifier = "Title 101"
    name = "Title 101"
    url = "/title-101/"
    weight = 2
[[menu.mobile]]
    identifier = "Underwriting"
    name = "Underwriting"
    url = "/underwriting/"
    weight = 3
[[menu.mobile]]
    identifier = "Title Calculators"
    name = "Title Calculators"
    url = "/title-calculator/"
    weight = 4
[[menu.mobile]]
    identifier = "Locations"
    name = "Locations"
    url = "/locations/"
    weight = 5
[[menu.mobile]]
    identifier = "Contact Us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 6
[params.tracking]
    cloudinaryUrl = "https://res.cloudinary.com/onpointcustomhomes/image/upload"
[params.socialLinks]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishing_settings]
    site_in_production = true

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS"]

[params.algolia]
    appId = ""
    searchKey = ""
    indexName = ""

[params.extra_tools]
    algolia_search = false
    font_awesome = true
    floating_header = false