baseURL = "https://empower-title.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Example"
enableRobotsTXT = true

[params.meta]
description = "This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission."

[[menu.desktop]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.desktop]]
    identifier = "title-101"
    name = "Title 101"
    url = "/title-101/"
    weight = 2
[[menu.desktop]]
    identifier = "underwriting"
    name = "Underwriting"
    url = "/underwriting/"
    weight = 3
[[menu.desktop]]
    identifier = "title-calculator"
    name = "Title Calculators"
    url = "/title-calculator/"
    weight = 4
[[menu.desktop]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 5
[[menu.mobile]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.mobile]]
    identifier = "title-101"
    name = "Title 101"
    url = "/title-101/"
    weight = 2
[[menu.mobile]]
    identifier = "underwriting"
    name = "Underwriting"
    url = "/underwriting/"
    weight = 3
[[menu.mobile]]
    identifier = "title-calculator"
    name = "Title Calculators"
    url = "/title-calculator/"
    weight = 4
[[menu.mobile]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 5
[params.contactNumbers]
    Fax = "555.555.5555"
    Phone = "555.555.5555"
[params.Logos]
    darkLogo = "/pageimg/example-logo.png"
    logo = "https://res.cloudinary.com/onpointcustomhomes/image/upload/v1566604761/Empower%20Title/Empower_Logo.jpg"
    mobileLogo = "https://res.cloudinary.com/onpointcustomhomes/image/upload/v1566604761/Empower%20Title/Empower_Logo.jpg"
[params.utilityImages]
    thankyouBackground = "/pageimg/thank-you-contact.jpg"
[params.address]
    city = "Statesboro"
    state = "GA"
    street = "P.O. Box 134"
    zip = 30459
[params.email]
    email = "example@example.com"
[params.tracking]
    googleAnalytics = ""
    cloudinaryUrl = "https://res.cloudinary.com/onpointcustomhomes/image/upload"
[params.socialLinks]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishingSettings]
    siteinProduction = false

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    searchKey = ""
    indexName = ""

[params.extraTools]
    algoliaSearch = false
    fontAwesome = true
    floatingHeader = false