[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.55.0"
RUBY_VERSION = "2.6.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.0"

[[redirects]]
  from = "https://empower-title.netlify.app/*"
  to = "https://www.empowertitleco.com/:splat"
  status = 301
  force = true